import 'package:mockito/annotations.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

/// Mock definitions for connectivity-related classes
/// 
/// This file defines the mock classes that will be generated by build_runner
/// for testing connectivity functionality including network status checking
/// and connectivity change monitoring.
@GenerateMocks([
  Connectivity,
])
void main() {}
