import 'package:mockito/annotations.dart';
import 'package:http/http.dart' as http;

// Import the services that need mocking
import '../../lib/features/pantry/services/pantry_service.dart';
import '../../lib/services/category_service.dart';
import '../../lib/services/offline_storage_service.dart';
import '../../lib/services/sync_service.dart';

/// Mock definitions for pantry and storage services
/// 
/// This file defines the mock classes that will be generated by build_runner
/// for testing pantry functionality including:
/// - PantryService: API operations for pantry items
/// - CategoryService: Category management operations  
/// - OfflineStorageService: Local SQLite storage operations
/// - SyncService: Synchronization between local and remote data
/// - http.Client: HTTP operations
@GenerateMocks([
  PantryService,
  CategoryService,
  OfflineStorageService,
  SyncService,
  http.Client,
])
void main() {}
