import 'package:mockito/annotations.dart';
import 'package:speech_to_text/speech_to_text.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:permission_handler/permission_handler.dart';

// Import the services that need mocking
import '../../lib/services/voice_service.dart';

/// Mock definitions for voice-related services
/// 
/// This file defines the mock classes that will be generated by build_runner
/// for testing voice functionality including:
/// - VoiceService: Main voice processing service
/// - SpeechToText: Speech recognition functionality
/// - FlutterTts: Text-to-speech functionality
/// - PermissionHandler: Microphone permission handling
@GenerateMocks([
  VoiceService,
  SpeechToText,
  FlutterTts,
])
void main() {}
